export type FieldType = "text" | "number" | "date" | "select" | "textarea" | "email";

export interface FieldValidation {
  min?: number;
  max?: number;
  maxDate?: "today"; // prevents future dates
  minLength?: number;
  maxLength?: number;
}

export interface FieldDef {
  key: string;
  label: string;
  type: FieldType;
  required?: boolean;
  options?: string[]; // for select type
  placeholder?: string;
  validation?: FieldValidation;
}

export interface ModuleDef {
  id: number;
  slug: string;
  title: string;
  section: string;
  sectionSlug: string;
  fields: FieldDef[];
}

const STATUS_OPTIONS = ["Pending", "In Progress", "Completed", "Approved", "Rejected"];
const SHIFT_OPTIONS = ["Morning", "Afternoon", "Night"];
const RESULT_OPTIONS = ["Pass", "Fail", "Conditional"];
const DEPT_OPTIONS = ["Cutting", "Sewing", "Finishing", "Quality", "Stores", "Admin"];

// Helper to create common fields
const dateField = (key = "date", label = "Date"): FieldDef => ({ key, label, type: "date", required: true, validation: { maxDate: "today" } });
const styleField: FieldDef = { key: "styleNo", label: "Style No", type: "text", required: true };
const orderField: FieldDef = { key: "orderNo", label: "Order No", type: "text", required: true };
const buyerField: FieldDef = { key: "buyer", label: "Buyer", type: "text" };
const qtyField = (label = "Quantity"): FieldDef => ({ key: "quantity", label, type: "number", validation: { min: 0 } });
const remarksField: FieldDef = { key: "remarks", label: "Remarks", type: "textarea" };
const statusField: FieldDef = { key: "status", label: "Status", type: "select", options: STATUS_OPTIONS, required: true };
const shiftField: FieldDef = { key: "shift", label: "Shift", type: "select", options: SHIFT_OPTIONS };
const lineField: FieldDef = { key: "lineNo", label: "Line No", type: "text" };
const inspectorField: FieldDef = { key: "inspector", label: "Inspector", type: "text" };
const approvedByField: FieldDef = { key: "approvedBy", label: "Approved By", type: "text" };
const sectionField: FieldDef = { key: "section", label: "Section", type: "text" };
const resultField: FieldDef = { key: "result", label: "Result", type: "select", options: RESULT_OPTIONS };
const deptField: FieldDef = { key: "department", label: "Department", type: "select", options: DEPT_OPTIONS };

const SEC_PRE = "Pre Production Activities";
const SEC_CUT_PROD = "Cutting Production Activities";
const SEC_CUT_QC = "Cutting Quality Activities";
const SEC_SEW_PROD = "Sewing Production Activities";
const SEC_SEW_QC = "Sewing Quality Activities";
const SEC_FIN_PROD = "Finishing Production Activities";
const SEC_FIN_QC = "Finishing Quality Activities";
const SEC_GENERAL = "General Activities";
const SEC_STORES = "Stores Activities";

export const modules: ModuleDef[] = [
  // ─── PRE PRODUCTION (1–20) ──────────────────
  { id: 1, slug: "style-file", title: "Style File", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField(), styleField, orderField, buyerField, { key: "description", label: "Description", type: "textarea" }, { key: "fabricType", label: "Fabric Type", type: "text" }, { key: "color", label: "Color", type: "text" }, { key: "season", label: "Season", type: "text" }, statusField, remarksField] },
  { id: 2, slug: "qc-qi-instructions", title: "QC/QI Instructions", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField(), styleField, orderField, buyerField, { key: "instructionType", label: "Instruction Type", type: "select", options: ["QC", "QI"] }, { key: "criticalPoints", label: "Critical Points", type: "textarea" }, { key: "issuedBy", label: "Issued By", type: "text" }, statusField, remarksField] },
  { id: 3, slug: "approved-sample", title: "Approved Sample", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField(), styleField, orderField, buyerField, { key: "sampleType", label: "Sample Type", type: "select", options: ["Proto", "Fit", "PP", "TOP", "Size Set", "Salesman"] }, approvedByField, { key: "approvalDate", label: "Approval Date", type: "date" }, statusField, remarksField] },
  { id: 4, slug: "fabric-color-trim-card", title: "Approved Fabric Color Continuity Card & Trim Card", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField(), styleField, orderField, { key: "fabricRef", label: "Fabric Reference", type: "text" }, { key: "colorCode", label: "Color Code", type: "text" }, { key: "trimDetails", label: "Trim Details", type: "textarea" }, approvedByField, statusField, remarksField] },
  { id: 5, slug: "lab-test-report", title: "Lab Test Report Procedure", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField(), styleField, { key: "fabricRef", label: "Fabric Reference", type: "text" }, { key: "testType", label: "Test Type", type: "select", options: ["Shrinkage", "Color Fastness", "Tensile Strength", "Pilling", "Tear Strength", "GSM"] }, { key: "labName", label: "Lab Name", type: "text" }, resultField, { key: "testValues", label: "Test Values", type: "text" }, statusField, remarksField] },
  { id: 6, slug: "fabric-inspection", title: "Fabric Inspection", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField(), { key: "fabricRef", label: "Fabric Reference", type: "text" }, { key: "rollNo", label: "Roll No", type: "text" }, { key: "lotNo", label: "Lot No", type: "text" }, qtyField("Received Qty (Yds)"), { key: "pointsPerYard", label: "Points/100 Sq Yd", type: "number" }, inspectorField, resultField, { key: "defectsFound", label: "Defects Found", type: "textarea" }, remarksField] },
  { id: 7, slug: "trim-inspection", title: "Trim Inspection", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField(), styleField, { key: "trimType", label: "Trim Type", type: "select", options: ["Button", "Zipper", "Label", "Thread", "Interlining", "Elastic", "Tape", "Other"] }, { key: "supplier", label: "Supplier", type: "text" }, qtyField("Received Qty"), { key: "sampleQty", label: "Sample Qty Checked", type: "number" }, inspectorField, resultField, { key: "defectsFound", label: "Defects Found", type: "textarea" }, remarksField] },
  { id: 8, slug: "calibration-equipment", title: "Calibration Of Measuring Equipment", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField("calibrationDate", "Calibration Date"), { key: "equipmentName", label: "Equipment Name", type: "text", required: true }, { key: "equipmentId", label: "Equipment ID", type: "text", required: true }, { key: "location", label: "Location", type: "text" }, { key: "calibratedBy", label: "Calibrated By", type: "text" }, { key: "nextDueDate", label: "Next Due Date", type: "date" }, resultField, { key: "certificate", label: "Certificate No", type: "text" }, remarksField] },
  { id: 9, slug: "fabric-shrinkage-report", title: "Fabric Shrinkage Report", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField(), { key: "fabricRef", label: "Fabric Reference", type: "text", required: true }, { key: "lotNo", label: "Lot No", type: "text" }, { key: "warpShrinkage", label: "Warp Shrinkage %", type: "number" }, { key: "weftShrinkage", label: "Weft Shrinkage %", type: "number" }, { key: "spiralityShrinkage", label: "Spirality %", type: "number" }, { key: "washType", label: "Wash Type", type: "text" }, { key: "temperature", label: "Temperature", type: "text" }, resultField, remarksField] },
  { id: 10, slug: "fabric-segregation", title: "Fabric Segregation Records", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField(), { key: "fabricRef", label: "Fabric Reference", type: "text", required: true }, { key: "lotNo", label: "Lot No", type: "text" }, { key: "shade", label: "Shade", type: "text" }, { key: "shadeGroup", label: "Shade Group", type: "text" }, qtyField("Quantity (Yds)"), { key: "noOfRolls", label: "No of Rolls", type: "number" }, statusField, remarksField] },
  { id: 11, slug: "cutting-pattern-approval", title: "Cutting Pattern Approval", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField(), styleField, orderField, { key: "size", label: "Size", type: "text" }, { key: "patternNo", label: "Pattern No", type: "text" }, { key: "checkedBy", label: "Checked By", type: "text" }, approvedByField, { key: "approvalDate", label: "Approval Date", type: "date" }, statusField, remarksField] },
  { id: 12, slug: "finish-pattern-marking", title: "Finish Pattern And Marking Board Approvals", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField(), styleField, orderField, { key: "size", label: "Size", type: "text" }, { key: "patternNo", label: "Pattern No", type: "text" }, { key: "markerLength", label: "Marker Length (m)", type: "number" }, { key: "markerWidth", label: "Marker Width (cm)", type: "number" }, approvedByField, statusField, remarksField] },
  { id: 13, slug: "line-sample", title: "Line Sample", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField(), styleField, orderField, buyerField, lineField, { key: "sampleQty", label: "Sample Qty", type: "number" }, approvedByField, { key: "approvalDate", label: "Approval Date", type: "date" }, statusField, remarksField] },
  { id: 14, slug: "measurement-sheet", title: "Measurement Sheet", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField(), styleField, orderField, { key: "size", label: "Size", type: "text", required: true }, { key: "pointOfMeasure", label: "Point of Measure", type: "text", required: true }, { key: "specValue", label: "Spec Value", type: "text" }, { key: "tolerance", label: "Tolerance (+/-)", type: "text" }, { key: "actualValue", label: "Actual Value", type: "text" }, resultField, remarksField] },
  { id: 15, slug: "critical-operation-id", title: "Critical Operation Identification", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField(), styleField, orderField, { key: "operationName", label: "Operation Name", type: "text", required: true }, { key: "machineType", label: "Machine Type", type: "text" }, { key: "skillLevel", label: "Skill Level Required", type: "select", options: ["Basic", "Medium", "High", "Expert"] }, { key: "controlMeasures", label: "Control Measures", type: "textarea" }, statusField, remarksField] },
  { id: 16, slug: "line-layout-manpower", title: "Line Layout And Manpower Allocation", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField(), styleField, orderField, lineField, { key: "totalManpower", label: "Total Manpower", type: "number" }, { key: "operators", label: "No of Operators", type: "number" }, { key: "helpers", label: "No of Helpers", type: "number" }, { key: "target", label: "Target/Hr", type: "number" }, { key: "smv", label: "SMV", type: "number" }, statusField, remarksField] },
  { id: 17, slug: "fabric-trim-status", title: "Fabric & Trim Status Report", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField(), styleField, orderField, buyerField, { key: "itemType", label: "Item Type", type: "select", options: ["Fabric", "Trim"] }, { key: "itemDescription", label: "Item Description", type: "text" }, { key: "requiredQty", label: "Required Qty", type: "number" }, { key: "receivedQty", label: "Received Qty", type: "number" }, { key: "balanceQty", label: "Balance Qty", type: "number" }, { key: "etd", label: "ETD", type: "date" }, statusField, remarksField] },
  { id: 18, slug: "pp-meeting", title: "PP Meeting", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField(), styleField, orderField, buyerField, { key: "attendees", label: "Attendees", type: "textarea" }, { key: "agenda", label: "Agenda", type: "textarea" }, { key: "decisions", label: "Decisions", type: "textarea" }, { key: "actionItems", label: "Action Items", type: "textarea" }, { key: "nextMeetingDate", label: "Next Meeting Date", type: "date" }, statusField, remarksField] },
  { id: 19, slug: "pp-checklist", title: "PP Check List", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField(), styleField, orderField, buyerField, { key: "fabricApproved", label: "Fabric Approved", type: "select", options: ["Yes", "No", "Pending"] }, { key: "trimsApproved", label: "Trims Approved", type: "select", options: ["Yes", "No", "Pending"] }, { key: "patternsApproved", label: "Patterns Approved", type: "select", options: ["Yes", "No", "Pending"] }, { key: "sampleApproved", label: "Sample Approved", type: "select", options: ["Yes", "No", "Pending"] }, { key: "measurementApproved", label: "Measurement Approved", type: "select", options: ["Yes", "No", "Pending"] }, statusField, remarksField] },
  { id: 20, slug: "size-set-pilot-cut", title: "Size Set / Pilot Cut Approval", section: SEC_PRE, sectionSlug: "pre-production", fields: [dateField(), styleField, orderField, buyerField, { key: "type", label: "Type", type: "select", options: ["Size Set", "Pilot Cut"], required: true }, qtyField("Quantity"), { key: "sizes", label: "Sizes", type: "text" }, { key: "checkedBy", label: "Checked By", type: "text" }, approvedByField, statusField, remarksField] },

  // ─── CUTTING PRODUCTION (21–44) ──────────────
  { id: 21, slug: "cut-dept-structure", title: "Department Structure & Manpower Budget", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), deptField, { key: "designation", label: "Designation", type: "text", required: true }, { key: "budgetedManpower", label: "Budgeted Manpower", type: "number" }, { key: "actualManpower", label: "Actual Manpower", type: "number" }, { key: "variance", label: "Variance", type: "number" }, statusField, remarksField] },
  { id: 22, slug: "cut-attendance", title: "Section Attendance Register", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), sectionField, shiftField, { key: "totalStaff", label: "Total Staff", type: "number" }, { key: "present", label: "Present", type: "number" }, { key: "absent", label: "Absent", type: "number" }, { key: "leave", label: "On Leave", type: "number" }, { key: "ot", label: "OT Count", type: "number" }, remarksField] },
  { id: 23, slug: "cut-stores-requisition", title: "Stores Requisition (General Items)", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), { key: "requisitionNo", label: "Requisition No", type: "text", required: true }, sectionField, { key: "itemDescription", label: "Item Description", type: "text", required: true }, qtyField("Quantity Required"), { key: "unit", label: "Unit", type: "text" }, { key: "requestedBy", label: "Requested By", type: "text" }, approvedByField, statusField, remarksField] },
  { id: 24, slug: "cutting-production-plan", title: "Cutting Production Plan", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), styleField, orderField, buyerField, { key: "plannedQty", label: "Planned Qty", type: "number", required: true }, { key: "noOfLays", label: "No of Lays", type: "number" }, { key: "startDate", label: "Start Date", type: "date" }, { key: "endDate", label: "End Date", type: "date" }, statusField, remarksField] },
  { id: 25, slug: "cut-style-file", title: "Style File", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), styleField, orderField, buyerField, { key: "description", label: "Description", type: "textarea" }, { key: "fabricType", label: "Fabric Type", type: "text" }, statusField, remarksField] },
  { id: 26, slug: "bulk-cut-procedure", title: "Bulk Cut Procedure", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), styleField, orderField, { key: "cutNo", label: "Cut No", type: "text", required: true }, { key: "noOfPlies", label: "No of Plies", type: "number" }, { key: "fabricType", label: "Fabric Type", type: "text" }, { key: "markerLength", label: "Marker Length (m)", type: "number" }, { key: "cuttingMethod", label: "Cutting Method", type: "select", options: ["Manual", "Auto Cutter", "Band Knife"] }, statusField, remarksField] },
  { id: 27, slug: "cutting-instruction", title: "Cutting Instruction (CI)", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), styleField, orderField, buyerField, { key: "ciNo", label: "CI No", type: "text", required: true }, { key: "color", label: "Color", type: "text" }, { key: "sizes", label: "Sizes", type: "text" }, qtyField("Total Qty"), { key: "issuedBy", label: "Issued By", type: "text" }, statusField, remarksField] },
  { id: 28, slug: "distribution-plan", title: "Distribution Plan", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), styleField, orderField, { key: "color", label: "Color", type: "text" }, { key: "sizes", label: "Sizes Breakdown", type: "textarea" }, qtyField("Total Qty"), { key: "assignedLine", label: "Assigned Line", type: "text" }, statusField, remarksField] },
  { id: 29, slug: "approved-marker", title: "Approved Marker", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), styleField, orderField, { key: "markerNo", label: "Marker No", type: "text", required: true }, { key: "markerLength", label: "Marker Length (m)", type: "number" }, { key: "markerWidth", label: "Marker Width (cm)", type: "number" }, { key: "efficiency", label: "Efficiency %", type: "number" }, { key: "noOfSizes", label: "No of Sizes", type: "number" }, approvedByField, statusField, remarksField] },
  { id: 30, slug: "style-cut-plan", title: "Style Cut Plan", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), styleField, orderField, buyerField, { key: "totalOrderQty", label: "Total Order Qty", type: "number" }, { key: "cutQty", label: "Cut Qty", type: "number" }, { key: "balanceQty", label: "Balance Qty", type: "number" }, { key: "plannedDate", label: "Planned Date", type: "date" }, statusField, remarksField] },
  { id: 31, slug: "day-cut-plan", title: "Day Cut Plan", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), styleField, orderField, { key: "color", label: "Color", type: "text" }, { key: "plannedQty", label: "Planned Qty", type: "number", required: true }, { key: "actualQty", label: "Actual Qty", type: "number" }, { key: "noOfLays", label: "No of Lays", type: "number" }, { key: "noOfPlies", label: "No of Plies", type: "number" }, statusField, remarksField] },
  { id: 32, slug: "fabric-requisition", title: "Fabric Requisition", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), { key: "requisitionNo", label: "Requisition No", type: "text", required: true }, styleField, orderField, { key: "fabricRef", label: "Fabric Reference", type: "text" }, { key: "color", label: "Color", type: "text" }, qtyField("Required Qty (Yds)"), { key: "requestedBy", label: "Requested By", type: "text" }, statusField, remarksField] },
  { id: 33, slug: "fabric-receiving", title: "Fabric Receiving Record", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), { key: "grnNo", label: "GRN No", type: "text", required: true }, { key: "fabricRef", label: "Fabric Reference", type: "text" }, { key: "supplier", label: "Supplier", type: "text" }, { key: "rollNo", label: "Roll No", type: "text" }, qtyField("Received Qty (Yds)"), { key: "receivedBy", label: "Received By", type: "text" }, statusField, remarksField] },
  { id: 34, slug: "layer-sheet", title: "Layer Sheet", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), styleField, { key: "cutNo", label: "Cut No", type: "text", required: true }, { key: "color", label: "Color", type: "text" }, { key: "layNo", label: "Lay No", type: "text" }, { key: "noOfPlies", label: "No of Plies", type: "number" }, { key: "markerLength", label: "Marker Length", type: "number" }, { key: "fabricUsed", label: "Fabric Used (Yds)", type: "number" }, remarksField] },
  { id: 35, slug: "bundle-guide-chart", title: "Bundle Guide Chart", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), styleField, orderField, { key: "cutNo", label: "Cut No", type: "text", required: true }, { key: "color", label: "Color", type: "text" }, { key: "size", label: "Size", type: "text" }, { key: "bundleFrom", label: "Bundle From", type: "number" }, { key: "bundleTo", label: "Bundle To", type: "number" }, { key: "pcsPerBundle", label: "Pcs Per Bundle", type: "number" }, remarksField] },
  { id: 36, slug: "day-issuing-plan", title: "Day Issuing Plan", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), styleField, orderField, lineField, { key: "plannedIssueQty", label: "Planned Issue Qty", type: "number", required: true }, { key: "actualIssueQty", label: "Actual Issue Qty", type: "number" }, { key: "sizes", label: "Sizes", type: "text" }, { key: "issuedBy", label: "Issued By", type: "text" }, statusField, remarksField] },
  { id: 37, slug: "panel-numbering", title: "Numbering Of Each Panel", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), styleField, { key: "cutNo", label: "Cut No", type: "text", required: true }, { key: "color", label: "Color", type: "text" }, { key: "panelName", label: "Panel Name", type: "text" }, { key: "fromNo", label: "From No", type: "number" }, { key: "toNo", label: "To No", type: "number" }, { key: "doneBy", label: "Done By", type: "text" }, statusField, remarksField] },
  { id: 38, slug: "bundle-card", title: "Bundle Card", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), styleField, orderField, { key: "bundleNo", label: "Bundle No", type: "text", required: true }, { key: "cutNo", label: "Cut No", type: "text" }, { key: "color", label: "Color", type: "text" }, { key: "size", label: "Size", type: "text" }, qtyField("Pieces"), lineField, statusField, remarksField] },
  { id: 39, slug: "bundle-sorting", title: "Bundle Sorting", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), styleField, orderField, { key: "cutNo", label: "Cut No", type: "text" }, { key: "totalBundles", label: "Total Bundles", type: "number" }, { key: "sortedBundles", label: "Sorted Bundles", type: "number" }, { key: "sortedBy", label: "Sorted By", type: "text" }, lineField, statusField, remarksField] },
  { id: 40, slug: "cutting-wip-report", title: "Cutting WIP Report", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), styleField, orderField, { key: "cutQty", label: "Cut Qty", type: "number" }, { key: "numberedQty", label: "Numbered Qty", type: "number" }, { key: "bundledQty", label: "Bundled Qty", type: "number" }, { key: "issuedQty", label: "Issued Qty", type: "number" }, { key: "wipBalance", label: "WIP Balance", type: "number" }, statusField, remarksField] },
  { id: 41, slug: "print-emb-records", title: "Printing Embroidery Sending And Receiving Records", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), styleField, orderField, { key: "processType", label: "Process Type", type: "select", options: ["Printing", "Embroidery"] }, { key: "sentQty", label: "Sent Qty", type: "number" }, { key: "receivedQty", label: "Received Qty", type: "number" }, { key: "sentDate", label: "Sent Date", type: "date" }, { key: "receivedDate", label: "Received Date", type: "date" }, { key: "vendor", label: "Vendor", type: "text" }, statusField, remarksField] },
  { id: 42, slug: "issuing-records", title: "Issuing Records", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), styleField, orderField, lineField, { key: "issueNo", label: "Issue No", type: "text", required: true }, qtyField("Issued Qty"), { key: "sizes", label: "Sizes", type: "text" }, { key: "issuedBy", label: "Issued By", type: "text" }, { key: "receivedBy", label: "Received By", type: "text" }, remarksField] },
  { id: 43, slug: "goods-return-records", title: "Goods Return Records (Fabric & General Items)", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), { key: "returnNo", label: "Return No", type: "text", required: true }, { key: "itemType", label: "Item Type", type: "select", options: ["Fabric", "General Items"] }, { key: "itemDescription", label: "Item Description", type: "text" }, qtyField("Return Qty"), { key: "reason", label: "Reason", type: "textarea" }, { key: "returnedBy", label: "Returned By", type: "text" }, statusField, remarksField] },
  { id: 44, slug: "cutting-reconciliation", title: "Cutting Reconciliation", section: SEC_CUT_PROD, sectionSlug: "cutting-production", fields: [dateField(), styleField, orderField, buyerField, { key: "orderQty", label: "Order Qty", type: "number" }, { key: "cutQty", label: "Cut Qty", type: "number" }, { key: "issuedQty", label: "Issued Qty", type: "number" }, { key: "rejectQty", label: "Reject Qty", type: "number" }, { key: "balanceQty", label: "Balance Qty", type: "number" }, statusField, remarksField] },

  // ─── CUTTING QUALITY (45–57) ─────────────────
  { id: 45, slug: "cq-dept-structure", title: "Department Structure & Manpower Budget", section: SEC_CUT_QC, sectionSlug: "cutting-quality", fields: [dateField(), deptField, { key: "designation", label: "Designation", type: "text", required: true }, { key: "budgetedManpower", label: "Budgeted Manpower", type: "number" }, { key: "actualManpower", label: "Actual Manpower", type: "number" }, { key: "variance", label: "Variance", type: "number" }, statusField, remarksField] },
  { id: 46, slug: "cq-attendance", title: "Section Attendance Register", section: SEC_CUT_QC, sectionSlug: "cutting-quality", fields: [dateField(), sectionField, shiftField, { key: "totalStaff", label: "Total Staff", type: "number" }, { key: "present", label: "Present", type: "number" }, { key: "absent", label: "Absent", type: "number" }, { key: "leave", label: "On Leave", type: "number" }, remarksField] },
  { id: 47, slug: "cq-qc-qi-instructions", title: "QC/QI Instructions", section: SEC_CUT_QC, sectionSlug: "cutting-quality", fields: [dateField(), styleField, orderField, { key: "instructionType", label: "Instruction Type", type: "select", options: ["QC", "QI"] }, { key: "criticalPoints", label: "Critical Points", type: "textarea" }, { key: "issuedBy", label: "Issued By", type: "text" }, statusField, remarksField] },
  { id: 48, slug: "fabric-relaxing", title: "Fabric Relaxing", section: SEC_CUT_QC, sectionSlug: "cutting-quality", fields: [dateField(), { key: "fabricRef", label: "Fabric Reference", type: "text", required: true }, { key: "rollNo", label: "Roll No", type: "text" }, { key: "relaxingTime", label: "Relaxing Time (hrs)", type: "number" }, { key: "startTime", label: "Start Time", type: "text" }, { key: "endTime", label: "End Time", type: "text" }, inspectorField, resultField, remarksField] },
  { id: 49, slug: "marker-checking", title: "Marker Checking", section: SEC_CUT_QC, sectionSlug: "cutting-quality", fields: [dateField(), styleField, { key: "markerNo", label: "Marker No", type: "text", required: true }, { key: "markerLength", label: "Marker Length (m)", type: "number" }, { key: "efficiency", label: "Efficiency %", type: "number" }, { key: "sizesChecked", label: "Sizes Checked", type: "text" }, inspectorField, resultField, remarksField] },
  { id: 50, slug: "spreading-checking", title: "Spreading Checking", section: SEC_CUT_QC, sectionSlug: "cutting-quality", fields: [dateField(), styleField, { key: "cutNo", label: "Cut No", type: "text" }, { key: "layNo", label: "Lay No", type: "text" }, { key: "noOfPlies", label: "No of Plies", type: "number" }, { key: "spreadingMethod", label: "Spreading Method", type: "select", options: ["Face Up", "Face Down", "Face to Face"] }, inspectorField, resultField, { key: "defectsFound", label: "Defects Found", type: "textarea" }, remarksField] },
  { id: 51, slug: "cut-inspection", title: "Cut Inspection", section: SEC_CUT_QC, sectionSlug: "cutting-quality", fields: [dateField(), styleField, { key: "cutNo", label: "Cut No", type: "text", required: true }, qtyField("Inspected Qty"), { key: "passQty", label: "Pass Qty", type: "number" }, { key: "failQty", label: "Fail Qty", type: "number" }, inspectorField, resultField, { key: "defectsFound", label: "Defects Found", type: "textarea" }, remarksField] },
  { id: 52, slug: "cut-panel-inspection", title: "Cut Panel Inspection", section: SEC_CUT_QC, sectionSlug: "cutting-quality", fields: [dateField(), styleField, { key: "cutNo", label: "Cut No", type: "text", required: true }, { key: "panelName", label: "Panel Name", type: "text" }, qtyField("Inspected Qty"), { key: "defectQty", label: "Defect Qty", type: "number" }, { key: "defectType", label: "Defect Type", type: "text" }, inspectorField, resultField, remarksField] },
  { id: 53, slug: "daily-cut-panel-replacement", title: "Daily Cut Panel Replacement", section: SEC_CUT_QC, sectionSlug: "cutting-quality", fields: [dateField(), styleField, { key: "cutNo", label: "Cut No", type: "text" }, { key: "panelName", label: "Panel Name", type: "text" }, { key: "defectType", label: "Defect Type", type: "text" }, { key: "replacedQty", label: "Replaced Qty", type: "number" }, { key: "replacedBy", label: "Replaced By", type: "text" }, remarksField] },
  { id: 54, slug: "monthly-cut-panel-rejects", title: "Monthly Summary Cut Panel Rejects", section: SEC_CUT_QC, sectionSlug: "cutting-quality", fields: [dateField("month", "Month"), styleField, orderField, { key: "totalInspected", label: "Total Inspected", type: "number" }, { key: "totalRejected", label: "Total Rejected", type: "number" }, { key: "rejectPercent", label: "Reject %", type: "number" }, { key: "topDefect", label: "Top Defect", type: "text" }, remarksField] },
  { id: 55, slug: "printing-inspection", title: "Printing Inspection", section: SEC_CUT_QC, sectionSlug: "cutting-quality", fields: [dateField(), styleField, orderField, { key: "printType", label: "Print Type", type: "text" }, qtyField("Inspected Qty"), { key: "passQty", label: "Pass Qty", type: "number" }, { key: "failQty", label: "Fail Qty", type: "number" }, inspectorField, resultField, { key: "defectsFound", label: "Defects Found", type: "textarea" }, remarksField] },
  { id: 56, slug: "embroidery-inspection", title: "Embroidery Inspection", section: SEC_CUT_QC, sectionSlug: "cutting-quality", fields: [dateField(), styleField, orderField, { key: "embType", label: "Embroidery Type", type: "text" }, qtyField("Inspected Qty"), { key: "passQty", label: "Pass Qty", type: "number" }, { key: "failQty", label: "Fail Qty", type: "number" }, inspectorField, resultField, { key: "defectsFound", label: "Defects Found", type: "textarea" }, remarksField] },
  { id: 57, slug: "fusing-inspection", title: "Fusing Inspection", section: SEC_CUT_QC, sectionSlug: "cutting-quality", fields: [dateField(), styleField, { key: "fusingTemp", label: "Fusing Temperature", type: "text" }, { key: "pressure", label: "Pressure", type: "text" }, { key: "time", label: "Time (sec)", type: "number" }, qtyField("Inspected Qty"), inspectorField, resultField, { key: "bondStrength", label: "Bond Strength", type: "select", options: ["Good", "Weak", "Fail"] }, remarksField] },

  // ─── SEWING PRODUCTION (58–81) ──────────────
  { id: 58, slug: "sew-dept-structure", title: "Department Structure & Manpower Budget", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), deptField, { key: "designation", label: "Designation", type: "text", required: true }, { key: "budgetedManpower", label: "Budgeted Manpower", type: "number" }, { key: "actualManpower", label: "Actual Manpower", type: "number" }, { key: "variance", label: "Variance", type: "number" }, statusField, remarksField] },
  { id: 59, slug: "sew-attendance", title: "Section Attendance Register", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), sectionField, shiftField, { key: "totalStaff", label: "Total Staff", type: "number" }, { key: "present", label: "Present", type: "number" }, { key: "absent", label: "Absent", type: "number" }, { key: "leave", label: "On Leave", type: "number" }, { key: "ot", label: "OT Count", type: "number" }, remarksField] },
  { id: 60, slug: "sew-style-file", title: "Style File", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), styleField, orderField, buyerField, { key: "description", label: "Description", type: "textarea" }, { key: "fabricType", label: "Fabric Type", type: "text" }, statusField, remarksField] },
  { id: 61, slug: "sew-stores-requisition", title: "Stores Requisition", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), { key: "requisitionNo", label: "Requisition No", type: "text", required: true }, sectionField, { key: "itemDescription", label: "Item Description", type: "text", required: true }, qtyField("Quantity Required"), { key: "unit", label: "Unit", type: "text" }, { key: "requestedBy", label: "Requested By", type: "text" }, statusField, remarksField] },
  { id: 62, slug: "approved-sample-line", title: "Approved Sample, Line Sample And Finished Patterns", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), styleField, orderField, buyerField, { key: "sampleType", label: "Type", type: "select", options: ["Approved Sample", "Line Sample", "Finished Pattern"] }, approvedByField, statusField, remarksField] },
  { id: 63, slug: "sew-production-plan", title: "Production Plan", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), styleField, orderField, buyerField, lineField, { key: "plannedQty", label: "Planned Qty", type: "number" }, { key: "smv", label: "SMV", type: "number" }, { key: "target", label: "Target/Hr", type: "number" }, { key: "startDate", label: "Start Date", type: "date" }, { key: "endDate", label: "End Date", type: "date" }, statusField, remarksField] },
  { id: 64, slug: "manpower-allocation", title: "Manpower Allocation & Transfer Records", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), lineField, { key: "operatorName", label: "Operator Name", type: "text", required: true }, { key: "operatorId", label: "Operator ID", type: "text" }, { key: "fromLine", label: "From Line", type: "text" }, { key: "toLine", label: "To Line", type: "text" }, { key: "operation", label: "Operation", type: "text" }, { key: "reason", label: "Reason", type: "textarea" }, statusField, remarksField] },
  { id: 65, slug: "input-man-job", title: "Input Man And Job Description", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), lineField, styleField, { key: "operationNo", label: "Operation No", type: "text" }, { key: "operationName", label: "Operation Name", type: "text", required: true }, { key: "machineType", label: "Machine Type", type: "text" }, { key: "smv", label: "SMV", type: "number" }, { key: "operatorName", label: "Operator Name", type: "text" }, remarksField] },
  { id: 66, slug: "individual-hourly-production", title: "Individual Hourly Production Report", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), lineField, { key: "operatorName", label: "Operator Name", type: "text", required: true }, { key: "operatorId", label: "Operator ID", type: "text" }, { key: "operation", label: "Operation", type: "text" }, { key: "target", label: "Target", type: "number" }, { key: "h1", label: "Hr 1", type: "number" }, { key: "h2", label: "Hr 2", type: "number" }, { key: "h3", label: "Hr 3", type: "number" }, { key: "h4", label: "Hr 4", type: "number" }, { key: "h5", label: "Hr 5", type: "number" }, { key: "h6", label: "Hr 6", type: "number" }, { key: "h7", label: "Hr 7", type: "number" }, { key: "h8", label: "Hr 8", type: "number" }, { key: "total", label: "Total", type: "number" }, remarksField] },
  { id: 67, slug: "factory-hourly-production", title: "Factory Hourly Production Report", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), shiftField, lineField, styleField, { key: "target", label: "Target", type: "number" }, { key: "h1", label: "Hr 1", type: "number" }, { key: "h2", label: "Hr 2", type: "number" }, { key: "h3", label: "Hr 3", type: "number" }, { key: "h4", label: "Hr 4", type: "number" }, { key: "h5", label: "Hr 5", type: "number" }, { key: "h6", label: "Hr 6", type: "number" }, { key: "h7", label: "Hr 7", type: "number" }, { key: "h8", label: "Hr 8", type: "number" }, { key: "total", label: "Total", type: "number" }, remarksField] },
  { id: 68, slug: "daily-sewing-production", title: "Daily Sewing Production Report", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), lineField, styleField, orderField, shiftField, { key: "target", label: "Daily Target", type: "number" }, { key: "output", label: "Daily Output", type: "number" }, { key: "efficiency", label: "Efficiency %", type: "number" }, { key: "manpower", label: "Manpower", type: "number" }, { key: "smv", label: "SMV", type: "number" }, remarksField] },
  { id: 69, slug: "sew-bundle-tracking", title: "Bundle Tracking", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), lineField, styleField, { key: "bundleNo", label: "Bundle No", type: "text", required: true }, { key: "size", label: "Size", type: "text" }, qtyField("Pieces"), { key: "currentOperation", label: "Current Operation", type: "text" }, statusField, remarksField] },
  { id: 70, slug: "revision-layout-target", title: "Revision Of Layout & Target", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), lineField, styleField, { key: "previousTarget", label: "Previous Target", type: "number" }, { key: "revisedTarget", label: "Revised Target", type: "number" }, { key: "previousManpower", label: "Previous Manpower", type: "number" }, { key: "revisedManpower", label: "Revised Manpower", type: "number" }, { key: "reason", label: "Reason", type: "textarea" }, approvedByField, remarksField] },
  { id: 71, slug: "daily-line-pocket-meeting", title: "Daily Line Pocket Meeting", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), lineField, styleField, shiftField, { key: "attendees", label: "Attendees", type: "textarea" }, { key: "issues", label: "Issues Discussed", type: "textarea" }, { key: "actions", label: "Action Items", type: "textarea" }, remarksField] },
  { id: 72, slug: "daily-line-forecast", title: "Daily Line Forecast Meeting", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), lineField, styleField, { key: "currentOutput", label: "Current Output", type: "number" }, { key: "forecastOutput", label: "Forecast Output", type: "number" }, { key: "bottlenecks", label: "Bottlenecks", type: "textarea" }, { key: "solutions", label: "Solutions", type: "textarea" }, remarksField] },
  { id: 73, slug: "overtime-plan", title: "Over Time Plan & Approval", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), lineField, sectionField, { key: "otHours", label: "OT Hours", type: "number", required: true }, { key: "noOfWorkers", label: "No of Workers", type: "number" }, { key: "reason", label: "Reason", type: "textarea" }, { key: "requestedBy", label: "Requested By", type: "text" }, approvedByField, statusField, remarksField] },
  { id: 74, slug: "lost-time-records", title: "Lost Time Records", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), lineField, shiftField, { key: "lostTimeMinutes", label: "Lost Time (min)", type: "number", required: true }, { key: "reason", label: "Reason", type: "select", options: ["Machine Breakdown", "No Input", "Power Failure", "Meeting", "Changeover", "Other"] }, { key: "description", label: "Description", type: "textarea" }, { key: "startTime", label: "Start Time", type: "text" }, { key: "endTime", label: "End Time", type: "text" }, remarksField] },
  { id: 75, slug: "bottleneck-solving", title: "Bottleneck Solving Procedure", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), lineField, styleField, { key: "operationName", label: "Bottleneck Operation", type: "text", required: true }, { key: "currentOutput", label: "Current Output", type: "number" }, { key: "targetOutput", label: "Target Output", type: "number" }, { key: "rootCause", label: "Root Cause", type: "textarea" }, { key: "action", label: "Action Taken", type: "textarea" }, { key: "result", label: "Result", type: "textarea" }, statusField, remarksField] },
  { id: 76, slug: "daily-efficiency-report", title: "Daily Efficiency Report", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), lineField, styleField, shiftField, { key: "manpower", label: "Manpower", type: "number" }, { key: "workingMinutes", label: "Working Minutes", type: "number" }, { key: "totalOutput", label: "Total Output", type: "number" }, { key: "smv", label: "SMV", type: "number" }, { key: "earnedMinutes", label: "Earned Minutes", type: "number" }, { key: "efficiency", label: "Efficiency %", type: "number" }, remarksField] },
  { id: 77, slug: "skill-inventory", title: "Skill Inventory", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), { key: "operatorName", label: "Operator Name", type: "text", required: true }, { key: "operatorId", label: "Operator ID", type: "text" }, lineField, { key: "operation", label: "Operation", type: "text" }, { key: "machineType", label: "Machine Type", type: "text" }, { key: "skillLevel", label: "Skill Level", type: "select", options: ["Trainee", "Grade C", "Grade B", "Grade A", "Multi-Skill"] }, { key: "efficiency", label: "Efficiency %", type: "number" }, remarksField] },
  { id: 78, slug: "weekly-progress-meeting", title: "Weekly Progress Meeting", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), { key: "weekNo", label: "Week No", type: "text" }, { key: "attendees", label: "Attendees", type: "textarea" }, { key: "productionSummary", label: "Production Summary", type: "textarea" }, { key: "qualitySummary", label: "Quality Summary", type: "textarea" }, { key: "issues", label: "Issues", type: "textarea" }, { key: "actions", label: "Action Items", type: "textarea" }, remarksField] },
  { id: 79, slug: "visual-production-board", title: "Visual Production Board", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), lineField, styleField, shiftField, { key: "target", label: "Target", type: "number" }, { key: "actual", label: "Actual", type: "number" }, { key: "variance", label: "Variance", type: "number" }, { key: "efficiency", label: "Efficiency %", type: "number" }, { key: "qualityRate", label: "Quality Rate %", type: "number" }, remarksField] },
  { id: 80, slug: "goods-transfer-records", title: "Goods Transfer Records", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), { key: "gtnNo", label: "GTN No", type: "text", required: true }, styleField, orderField, { key: "fromDept", label: "From Department", type: "text" }, { key: "toDept", label: "To Department", type: "text" }, qtyField("Transfer Qty"), { key: "transferredBy", label: "Transferred By", type: "text" }, { key: "receivedBy", label: "Received By", type: "text" }, remarksField] },
  { id: 81, slug: "style-reconciliation", title: "Style Reconciliation", section: SEC_SEW_PROD, sectionSlug: "sewing-production", fields: [dateField(), styleField, orderField, buyerField, { key: "orderQty", label: "Order Qty", type: "number" }, { key: "cutQty", label: "Cut Qty", type: "number" }, { key: "sewOutput", label: "Sewing Output", type: "number" }, { key: "rejectQty", label: "Reject Qty", type: "number" }, { key: "balanceQty", label: "Balance Qty", type: "number" }, statusField, remarksField] },

  // ─── SEWING QUALITY (82–98) ─────────────────
  { id: 82, slug: "sq-dept-structure", title: "Department Structure & Manpower Budget", section: SEC_SEW_QC, sectionSlug: "sewing-quality", fields: [dateField(), deptField, { key: "designation", label: "Designation", type: "text", required: true }, { key: "budgetedManpower", label: "Budgeted Manpower", type: "number" }, { key: "actualManpower", label: "Actual Manpower", type: "number" }, { key: "variance", label: "Variance", type: "number" }, statusField, remarksField] },
  { id: 83, slug: "sq-attendance", title: "Section Attendance Register", section: SEC_SEW_QC, sectionSlug: "sewing-quality", fields: [dateField(), sectionField, shiftField, { key: "totalStaff", label: "Total Staff", type: "number" }, { key: "present", label: "Present", type: "number" }, { key: "absent", label: "Absent", type: "number" }, { key: "leave", label: "On Leave", type: "number" }, remarksField] },
  { id: 84, slug: "sq-qc-qi-instructions", title: "QC/QI Instructions", section: SEC_SEW_QC, sectionSlug: "sewing-quality", fields: [dateField(), styleField, orderField, { key: "instructionType", label: "Instruction Type", type: "select", options: ["QC", "QI"] }, { key: "criticalPoints", label: "Critical Points", type: "textarea" }, { key: "issuedBy", label: "Issued By", type: "text" }, statusField, remarksField] },
  { id: 85, slug: "line-feeding-report", title: "Line Feeding Report", section: SEC_SEW_QC, sectionSlug: "sewing-quality", fields: [dateField(), lineField, styleField, shiftField, { key: "inputQty", label: "Input Qty", type: "number" }, { key: "outputQty", label: "Output Qty", type: "number" }, { key: "balanceWip", label: "Balance WIP", type: "number" }, inspectorField, remarksField] },
  { id: 86, slug: "mockup-preparation", title: "Mockup Preparation", section: SEC_SEW_QC, sectionSlug: "sewing-quality", fields: [dateField(), styleField, orderField, lineField, { key: "mockupDetails", label: "Mockup Details", type: "textarea" }, { key: "preparedBy", label: "Prepared By", type: "text" }, approvedByField, statusField, remarksField] },
  { id: 87, slug: "machine-checking-report", title: "Machine Checking Report", section: SEC_SEW_QC, sectionSlug: "sewing-quality", fields: [dateField(), lineField, { key: "machineNo", label: "Machine No", type: "text", required: true }, { key: "machineType", label: "Machine Type", type: "text" }, { key: "needleType", label: "Needle Type", type: "text" }, { key: "threadTension", label: "Thread Tension", type: "select", options: ["OK", "Adjusted", "Needs Repair"] }, { key: "spi", label: "SPI", type: "number" }, inspectorField, resultField, remarksField] },
  { id: 88, slug: "pilot-run-evaluation", title: "Pilot Run / First Bundle Evaluation And Bulk Cut Approval", section: SEC_SEW_QC, sectionSlug: "sewing-quality", fields: [dateField(), styleField, orderField, lineField, { key: "evaluationType", label: "Type", type: "select", options: ["Pilot Run", "First Bundle", "Bulk Cut Approval"] }, qtyField("Evaluated Qty"), { key: "findings", label: "Findings", type: "textarea" }, inspectorField, approvedByField, resultField, remarksField] },
  { id: 89, slug: "sq-bundle-tracking", title: "Bundle Tracking", section: SEC_SEW_QC, sectionSlug: "sewing-quality", fields: [dateField(), lineField, styleField, { key: "bundleNo", label: "Bundle No", type: "text", required: true }, { key: "size", label: "Size", type: "text" }, qtyField("Pieces"), { key: "defectsFound", label: "Defects Found", type: "number" }, inspectorField, resultField, remarksField] },
  { id: 90, slug: "inline-quality-system", title: "Inline 7.0 Quality System", section: SEC_SEW_QC, sectionSlug: "sewing-quality", fields: [dateField(), lineField, styleField, shiftField, { key: "checkPoint", label: "Check Point", type: "text" }, { key: "checkedQty", label: "Checked Qty", type: "number" }, { key: "defectQty", label: "Defect Qty", type: "number" }, { key: "dhu", label: "DHU %", type: "number" }, inspectorField, resultField, remarksField] },
  { id: 91, slug: "hourly-quality-inprocess", title: "Hourly Quality Inspection Report - In Process (Section)", section: SEC_SEW_QC, sectionSlug: "sewing-quality", fields: [dateField(), lineField, styleField, sectionField, shiftField, { key: "h1Checked", label: "Hr 1 Checked", type: "number" }, { key: "h1Defect", label: "Hr 1 Defect", type: "number" }, { key: "h2Checked", label: "Hr 2 Checked", type: "number" }, { key: "h2Defect", label: "Hr 2 Defect", type: "number" }, { key: "h3Checked", label: "Hr 3 Checked", type: "number" }, { key: "h3Defect", label: "Hr 3 Defect", type: "number" }, { key: "h4Checked", label: "Hr 4 Checked", type: "number" }, { key: "h4Defect", label: "Hr 4 Defect", type: "number" }, { key: "totalChecked", label: "Total Checked", type: "number" }, { key: "totalDefects", label: "Total Defects", type: "number" }, { key: "dhu", label: "DHU %", type: "number" }, inspectorField, remarksField] },
  { id: 92, slug: "inprocess-monthly-summary", title: "In Process Monthly - Defects/Rejects Summary", section: SEC_SEW_QC, sectionSlug: "sewing-quality", fields: [dateField("month", "Month"), lineField, styleField, { key: "totalChecked", label: "Total Checked", type: "number" }, { key: "totalDefects", label: "Total Defects", type: "number" }, { key: "totalRejects", label: "Total Rejects", type: "number" }, { key: "dhu", label: "DHU %", type: "number" }, { key: "topDefects", label: "Top 5 Defects", type: "textarea" }, remarksField] },
  { id: 93, slug: "hourly-quality-endline", title: "Hourly Quality Inspection Report - End Line", section: SEC_SEW_QC, sectionSlug: "sewing-quality", fields: [dateField(), lineField, styleField, shiftField, { key: "h1Checked", label: "Hr 1 Checked", type: "number" }, { key: "h1Defect", label: "Hr 1 Defect", type: "number" }, { key: "h2Checked", label: "Hr 2 Checked", type: "number" }, { key: "h2Defect", label: "Hr 2 Defect", type: "number" }, { key: "h3Checked", label: "Hr 3 Checked", type: "number" }, { key: "h3Defect", label: "Hr 3 Defect", type: "number" }, { key: "h4Checked", label: "Hr 4 Checked", type: "number" }, { key: "h4Defect", label: "Hr 4 Defect", type: "number" }, { key: "totalChecked", label: "Total Checked", type: "number" }, { key: "totalDefects", label: "Total Defects", type: "number" }, { key: "dhu", label: "DHU %", type: "number" }, inspectorField, remarksField] },
  { id: 94, slug: "endline-monthly-summary", title: "End Line Defects/Rejects Monthly Summary", section: SEC_SEW_QC, sectionSlug: "sewing-quality", fields: [dateField("month", "Month"), lineField, styleField, { key: "totalChecked", label: "Total Checked", type: "number" }, { key: "totalDefects", label: "Total Defects", type: "number" }, { key: "totalRejects", label: "Total Rejects", type: "number" }, { key: "dhu", label: "DHU %", type: "number" }, { key: "topDefects", label: "Top 5 Defects", type: "textarea" }, remarksField] },
  { id: 95, slug: "button-pull-test", title: "Button Pull Test", section: SEC_SEW_QC, sectionSlug: "sewing-quality", fields: [dateField(), styleField, orderField, { key: "buttonType", label: "Button Type", type: "text" }, { key: "pullForce", label: "Pull Force (lbs)", type: "number" }, { key: "standard", label: "Standard (lbs)", type: "number" }, { key: "sampleQty", label: "Sample Qty Tested", type: "number" }, inspectorField, resultField, remarksField] },
  { id: 96, slug: "garments-measuring", title: "Garments Measuring", section: SEC_SEW_QC, sectionSlug: "sewing-quality", fields: [dateField(), styleField, orderField, { key: "size", label: "Size", type: "text", required: true }, { key: "pointOfMeasure", label: "Point of Measure", type: "text", required: true }, { key: "specValue", label: "Spec Value", type: "text" }, { key: "tolerance", label: "Tolerance (+/-)", type: "text" }, { key: "actualValue", label: "Actual Value", type: "text" }, inspectorField, resultField, remarksField] },
  { id: 97, slug: "end-table-aql", title: "End Table AQL Audit", section: SEC_SEW_QC, sectionSlug: "sewing-quality", fields: [dateField(), lineField, styleField, orderField, { key: "lotSize", label: "Lot Size", type: "number" }, { key: "sampleSize", label: "Sample Size", type: "number" }, { key: "aqlLevel", label: "AQL Level", type: "select", options: ["1.5", "2.5", "4.0", "6.5"] }, { key: "majorDefects", label: "Major Defects", type: "number" }, { key: "minorDefects", label: "Minor Defects", type: "number" }, inspectorField, resultField, remarksField] },
  { id: 98, slug: "monthly-aql-summary", title: "Monthly Summary Of AQL Audits", section: SEC_SEW_QC, sectionSlug: "sewing-quality", fields: [dateField("month", "Month"), lineField, { key: "totalLots", label: "Total Lots", type: "number" }, { key: "passedLots", label: "Passed Lots", type: "number" }, { key: "failedLots", label: "Failed Lots", type: "number" }, { key: "passRate", label: "Pass Rate %", type: "number" }, { key: "topDefects", label: "Top Defects", type: "textarea" }, remarksField] },

  // ─── FINISHING PRODUCTION (99–107) ──────────
  { id: 99, slug: "fin-dept-structure", title: "Department Structure & Manpower Budget", section: SEC_FIN_PROD, sectionSlug: "finishing-production", fields: [dateField(), deptField, { key: "designation", label: "Designation", type: "text", required: true }, { key: "budgetedManpower", label: "Budgeted Manpower", type: "number" }, { key: "actualManpower", label: "Actual Manpower", type: "number" }, { key: "variance", label: "Variance", type: "number" }, statusField, remarksField] },
  { id: 100, slug: "fin-attendance", title: "Section Attendance Register", section: SEC_FIN_PROD, sectionSlug: "finishing-production", fields: [dateField(), sectionField, shiftField, { key: "totalStaff", label: "Total Staff", type: "number" }, { key: "present", label: "Present", type: "number" }, { key: "absent", label: "Absent", type: "number" }, { key: "leave", label: "On Leave", type: "number" }, remarksField] },
  { id: 101, slug: "fin-style-file", title: "Style File", section: SEC_FIN_PROD, sectionSlug: "finishing-production", fields: [dateField(), styleField, orderField, buyerField, { key: "packingMethod", label: "Packing Method", type: "text" }, { key: "foldingMethod", label: "Folding Method", type: "text" }, statusField, remarksField] },
  { id: 102, slug: "fin-stores-requisition", title: "Stores Requisition", section: SEC_FIN_PROD, sectionSlug: "finishing-production", fields: [dateField(), { key: "requisitionNo", label: "Requisition No", type: "text", required: true }, { key: "itemDescription", label: "Item Description", type: "text", required: true }, qtyField("Quantity Required"), { key: "unit", label: "Unit", type: "text" }, { key: "requestedBy", label: "Requested By", type: "text" }, statusField, remarksField] },
  { id: 103, slug: "fin-production-receiving", title: "Production Receiving", section: SEC_FIN_PROD, sectionSlug: "finishing-production", fields: [dateField(), styleField, orderField, lineField, qtyField("Received Qty"), { key: "receivedBy", label: "Received By", type: "text" }, { key: "color", label: "Color", type: "text" }, { key: "sizes", label: "Sizes", type: "text" }, remarksField] },
  { id: 104, slug: "fin-hourly-production", title: "Hourly Production Report", section: SEC_FIN_PROD, sectionSlug: "finishing-production", fields: [dateField(), styleField, shiftField, { key: "process", label: "Process", type: "select", options: ["Thread Cutting", "Washing", "Pressing", "Folding", "Packing"] }, { key: "h1", label: "Hr 1", type: "number" }, { key: "h2", label: "Hr 2", type: "number" }, { key: "h3", label: "Hr 3", type: "number" }, { key: "h4", label: "Hr 4", type: "number" }, { key: "h5", label: "Hr 5", type: "number" }, { key: "h6", label: "Hr 6", type: "number" }, { key: "h7", label: "Hr 7", type: "number" }, { key: "h8", label: "Hr 8", type: "number" }, { key: "total", label: "Total", type: "number" }, remarksField] },
  { id: 105, slug: "fin-daily-wip", title: "Daily Finishing WIP Report", section: SEC_FIN_PROD, sectionSlug: "finishing-production", fields: [dateField(), styleField, orderField, { key: "inputQty", label: "Input Qty", type: "number" }, { key: "threadCut", label: "Thread Cut", type: "number" }, { key: "washed", label: "Washed", type: "number" }, { key: "pressed", label: "Pressed", type: "number" }, { key: "folded", label: "Folded", type: "number" }, { key: "packed", label: "Packed", type: "number" }, { key: "wipBalance", label: "WIP Balance", type: "number" }, remarksField] },
  { id: 106, slug: "fin-return-garments", title: "Finishing Return Record - Garments", section: SEC_FIN_PROD, sectionSlug: "finishing-production", fields: [dateField(), styleField, orderField, lineField, { key: "returnQty", label: "Return Qty", type: "number", required: true }, { key: "defectType", label: "Defect Type", type: "text" }, { key: "returnedBy", label: "Returned By", type: "text" }, { key: "receivedBy", label: "Received By", type: "text" }, remarksField] },
  { id: 107, slug: "fin-return-general", title: "Finishing Return Record - General Items & Accessories", section: SEC_FIN_PROD, sectionSlug: "finishing-production", fields: [dateField(), { key: "returnNo", label: "Return No", type: "text", required: true }, { key: "itemDescription", label: "Item Description", type: "text" }, qtyField("Return Qty"), { key: "reason", label: "Reason", type: "textarea" }, { key: "returnedBy", label: "Returned By", type: "text" }, statusField, remarksField] },

  // ─── FINISHING QUALITY (108–119) ────────────
  { id: 108, slug: "fq-dept-structure", title: "Department Structure & Manpower Budget", section: SEC_FIN_QC, sectionSlug: "finishing-quality", fields: [dateField(), deptField, { key: "designation", label: "Designation", type: "text", required: true }, { key: "budgetedManpower", label: "Budgeted Manpower", type: "number" }, { key: "actualManpower", label: "Actual Manpower", type: "number" }, { key: "variance", label: "Variance", type: "number" }, statusField, remarksField] },
  { id: 109, slug: "fq-attendance", title: "Section Attendance Register", section: SEC_FIN_QC, sectionSlug: "finishing-quality", fields: [dateField(), sectionField, shiftField, { key: "totalStaff", label: "Total Staff", type: "number" }, { key: "present", label: "Present", type: "number" }, { key: "absent", label: "Absent", type: "number" }, { key: "leave", label: "On Leave", type: "number" }, remarksField] },
  { id: 110, slug: "fq-qc-qi-instructions", title: "QC/QI Instructions", section: SEC_FIN_QC, sectionSlug: "finishing-quality", fields: [dateField(), styleField, orderField, { key: "instructionType", label: "Instruction Type", type: "select", options: ["QC", "QI"] }, { key: "criticalPoints", label: "Critical Points", type: "textarea" }, { key: "issuedBy", label: "Issued By", type: "text" }, statusField, remarksField] },
  { id: 111, slug: "approved-packing-sample", title: "Approved Packing Sample", section: SEC_FIN_QC, sectionSlug: "finishing-quality", fields: [dateField(), styleField, orderField, buyerField, { key: "packingMethod", label: "Packing Method", type: "text" }, { key: "polyBagSize", label: "Poly Bag Size", type: "text" }, { key: "cartonSize", label: "Carton Size", type: "text" }, approvedByField, statusField, remarksField] },
  { id: 112, slug: "fq-approved-trim-card", title: "Approved Trim Card", section: SEC_FIN_QC, sectionSlug: "finishing-quality", fields: [dateField(), styleField, orderField, buyerField, { key: "trimDetails", label: "Trim Details", type: "textarea" }, approvedByField, { key: "approvalDate", label: "Approval Date", type: "date" }, statusField, remarksField] },
  { id: 113, slug: "fin-hourly-quality", title: "Finishing Hourly Quality Inspection Report", section: SEC_FIN_QC, sectionSlug: "finishing-quality", fields: [dateField(), styleField, shiftField, { key: "h1Checked", label: "Hr 1 Checked", type: "number" }, { key: "h1Defect", label: "Hr 1 Defect", type: "number" }, { key: "h2Checked", label: "Hr 2 Checked", type: "number" }, { key: "h2Defect", label: "Hr 2 Defect", type: "number" }, { key: "h3Checked", label: "Hr 3 Checked", type: "number" }, { key: "h3Defect", label: "Hr 3 Defect", type: "number" }, { key: "h4Checked", label: "Hr 4 Checked", type: "number" }, { key: "h4Defect", label: "Hr 4 Defect", type: "number" }, { key: "totalChecked", label: "Total Checked", type: "number" }, { key: "totalDefects", label: "Total Defects", type: "number" }, inspectorField, remarksField] },
  { id: 114, slug: "fin-defect-monthly-summary", title: "Finishing Defect/Reject Monthly Summary", section: SEC_FIN_QC, sectionSlug: "finishing-quality", fields: [dateField("month", "Month"), styleField, { key: "totalChecked", label: "Total Checked", type: "number" }, { key: "totalDefects", label: "Total Defects", type: "number" }, { key: "totalRejects", label: "Total Rejects", type: "number" }, { key: "dhu", label: "DHU %", type: "number" }, { key: "topDefects", label: "Top Defects", type: "textarea" }, remarksField] },
  { id: 115, slug: "fin-aql-audit", title: "Finishing AQL Audit", section: SEC_FIN_QC, sectionSlug: "finishing-quality", fields: [dateField(), styleField, orderField, buyerField, { key: "lotSize", label: "Lot Size", type: "number" }, { key: "sampleSize", label: "Sample Size", type: "number" }, { key: "aqlLevel", label: "AQL Level", type: "select", options: ["1.5", "2.5", "4.0", "6.5"] }, { key: "majorDefects", label: "Major Defects", type: "number" }, { key: "minorDefects", label: "Minor Defects", type: "number" }, resultField, remarksField] },
  { id: 116, slug: "fin-aql-monthly-summary", title: "Finishing AQL Audit - Monthly Summary", section: SEC_FIN_QC, sectionSlug: "finishing-quality", fields: [dateField("month", "Month"), { key: "totalLots", label: "Total Lots", type: "number" }, { key: "passedLots", label: "Passed Lots", type: "number" }, { key: "failedLots", label: "Failed Lots", type: "number" }, { key: "passRate", label: "Pass Rate %", type: "number" }, { key: "topDefects", label: "Top Defects", type: "textarea" }, remarksField] },
  { id: 117, slug: "needle-detects-report", title: "Needle Detects Report", section: SEC_FIN_QC, sectionSlug: "finishing-quality", fields: [dateField(), lineField, styleField, { key: "machineNo", label: "Machine No", type: "text" }, { key: "detectedQty", label: "Detected Qty", type: "number" }, { key: "sensitivity", label: "Sensitivity Level", type: "text" }, { key: "testPiece", label: "Test Piece Result", type: "select", options: ["Pass", "Fail"] }, inspectorField, remarksField] },
  { id: 118, slug: "pre-final-inspection", title: "Pre Final Inspection Report - Internal", section: SEC_FIN_QC, sectionSlug: "finishing-quality", fields: [dateField(), styleField, orderField, buyerField, { key: "lotSize", label: "Lot Size", type: "number" }, { key: "sampleSize", label: "Sample Size", type: "number" }, { key: "majorDefects", label: "Major Defects", type: "number" }, { key: "minorDefects", label: "Minor Defects", type: "number" }, inspectorField, resultField, { key: "corrective", label: "Corrective Actions", type: "textarea" }, remarksField] },
  { id: 119, slug: "final-style-reconciliation", title: "Final Style Reconciliation", section: SEC_FIN_QC, sectionSlug: "finishing-quality", fields: [dateField(), styleField, orderField, buyerField, { key: "orderQty", label: "Order Qty", type: "number" }, { key: "cutQty", label: "Cut Qty", type: "number" }, { key: "sewOutput", label: "Sewing Output", type: "number" }, { key: "finOutput", label: "Finishing Output", type: "number" }, { key: "packedQty", label: "Packed Qty", type: "number" }, { key: "shortExcess", label: "Short/Excess", type: "number" }, remarksField] },

  // ─── GENERAL (120–121) ─────────────────────
  { id: 120, slug: "daily-factory-attendance", title: "Daily Factory Attendance Report", section: SEC_GENERAL, sectionSlug: "general", fields: [dateField(), { key: "totalEmployees", label: "Total Employees", type: "number" }, { key: "present", label: "Present", type: "number" }, { key: "absent", label: "Absent", type: "number" }, { key: "leave", label: "On Leave", type: "number" }, { key: "attendancePercent", label: "Attendance %", type: "number" }, shiftField, deptField, remarksField] },
  { id: 121, slug: "daily-factory-quality", title: "Daily Factory Quality Report", section: SEC_GENERAL, sectionSlug: "general", fields: [dateField(), { key: "totalChecked", label: "Total Checked", type: "number" }, { key: "totalDefects", label: "Total Defects", type: "number" }, { key: "totalRejects", label: "Total Rejects", type: "number" }, { key: "dhu", label: "DHU %", type: "number" }, { key: "rft", label: "RFT %", type: "number" }, { key: "topDefects", label: "Top Defects", type: "textarea" }, remarksField] },

  // ─── STORES (122–129) ──────────────────────
  { id: 122, slug: "trim-quality-inspection", title: "Trim Quality Standard And Inspection", section: SEC_STORES, sectionSlug: "stores", fields: [dateField(), { key: "trimType", label: "Trim Type", type: "text", required: true }, { key: "supplier", label: "Supplier", type: "text" }, qtyField("Received Qty"), { key: "sampleChecked", label: "Sample Checked", type: "number" }, inspectorField, resultField, { key: "defectsFound", label: "Defects Found", type: "textarea" }, remarksField] },
  { id: 123, slug: "daily-issuing-prep", title: "Production Plan And Daily Issuing Preparation", section: SEC_STORES, sectionSlug: "stores", fields: [dateField(), styleField, orderField, lineField, { key: "plannedIssueQty", label: "Planned Issue Qty", type: "number" }, { key: "actualIssueQty", label: "Actual Issue Qty", type: "number" }, { key: "itemType", label: "Item Type", type: "text" }, statusField, remarksField] },
  { id: 124, slug: "goods-issuing-procedure", title: "Goods Issuing Procedure", section: SEC_STORES, sectionSlug: "stores", fields: [dateField(), { key: "issueNo", label: "Issue No", type: "text", required: true }, styleField, orderField, { key: "itemDescription", label: "Item Description", type: "text" }, qtyField("Issue Qty"), { key: "issuedTo", label: "Issued To", type: "text" }, { key: "issuedBy", label: "Issued By", type: "text" }, remarksField] },
  { id: 125, slug: "goods-transfer-gtn", title: "Goods Transfer Procedure And GTN", section: SEC_STORES, sectionSlug: "stores", fields: [dateField(), { key: "gtnNo", label: "GTN No", type: "text", required: true }, { key: "fromLocation", label: "From Location", type: "text" }, { key: "toLocation", label: "To Location", type: "text" }, { key: "itemDescription", label: "Item Description", type: "text" }, qtyField("Transfer Qty"), { key: "transferredBy", label: "Transferred By", type: "text" }, remarksField] },
  { id: 126, slug: "bin-cards", title: "Bin Cards", section: SEC_STORES, sectionSlug: "stores", fields: [dateField(), { key: "binNo", label: "Bin No", type: "text", required: true }, { key: "itemDescription", label: "Item Description", type: "text", required: true }, { key: "openingBalance", label: "Opening Balance", type: "number" }, { key: "received", label: "Received", type: "number" }, { key: "issued", label: "Issued", type: "number" }, { key: "closingBalance", label: "Closing Balance", type: "number" }, { key: "unit", label: "Unit", type: "text" }, remarksField] },
  { id: 127, slug: "inventory-in-out", title: "Inventory Items In & Out Within The Companies", section: SEC_STORES, sectionSlug: "stores", fields: [dateField(), { key: "itemCode", label: "Item Code", type: "text", required: true }, { key: "itemDescription", label: "Item Description", type: "text" }, { key: "transactionType", label: "Transaction Type", type: "select", options: ["In", "Out", "Transfer"] }, qtyField("Quantity"), { key: "fromCompany", label: "From Company", type: "text" }, { key: "toCompany", label: "To Company", type: "text" }, { key: "documentRef", label: "Document Ref", type: "text" }, remarksField] },
  { id: 128, slug: "leftover-nonmoving", title: "Left Over Summary Records And Non-Moving Items", section: SEC_STORES, sectionSlug: "stores", fields: [dateField(), { key: "itemCode", label: "Item Code", type: "text" }, { key: "itemDescription", label: "Item Description", type: "text", required: true }, qtyField("Quantity"), { key: "value", label: "Value", type: "number" }, { key: "lastMovementDate", label: "Last Movement Date", type: "date" }, { key: "agingDays", label: "Aging (Days)", type: "number" }, { key: "action", label: "Action", type: "select", options: ["Keep", "Return", "Dispose", "Transfer"] }, remarksField] },
  { id: 129, slug: "stores-reconciliation", title: "Stores Reconciliation", section: SEC_STORES, sectionSlug: "stores", fields: [dateField(), styleField, orderField, { key: "itemDescription", label: "Item Description", type: "text" }, { key: "requiredQty", label: "Required Qty", type: "number" }, { key: "receivedQty", label: "Received Qty", type: "number" }, { key: "issuedQty", label: "Issued Qty", type: "number" }, { key: "balanceQty", label: "Balance Qty", type: "number" }, { key: "returnQty", label: "Return Qty", type: "number" }, statusField, remarksField] },
];

// Section metadata
export interface SectionDef {
  slug: string;
  label: string;
  icon: string; // lucide icon name
}

export const sections: SectionDef[] = [
  { slug: "pre-production", label: "Pre Production", icon: "ClipboardCheck" },
  { slug: "cutting-production", label: "Cutting Production", icon: "Scissors" },
  { slug: "cutting-quality", label: "Cutting Quality", icon: "ShieldCheck" },
  { slug: "sewing-production", label: "Sewing Production", icon: "Factory" },
  { slug: "sewing-quality", label: "Sewing Quality", icon: "ShieldCheck" },
  { slug: "finishing-production", label: "Finishing Production", icon: "Package" },
  { slug: "finishing-quality", label: "Finishing Quality", icon: "ShieldCheck" },
  { slug: "general", label: "General", icon: "Building" },
  { slug: "stores", label: "Stores", icon: "Warehouse" },
];

export function getModulesBySection(sectionSlug: string): ModuleDef[] {
  return modules.filter(m => m.sectionSlug === sectionSlug);
}

export function getModuleBySlug(slug: string): ModuleDef | undefined {
  return modules.find(m => m.slug === slug);
}
